# Generated by Django 3.2.20 on 2023-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('0', 'UAH'), ('1', 'USD'), ('2', 'EUR')], default='1', max_length=3),
        ),
    ]
