# Generated by Django 3.2.20 on 2024-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_email', models.EmailField(max_length=254, verbose_name='admin@example.com')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
