name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Flake8
      run: |
        flake8 .

    - name: Run Pytest
      run: |
        pytest .

  docker:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          sleep 10

      - name: Check running containers
        run: docker ps

      - name: Run health check
        run: curl -f http://localhost || (docker-compose logs && exit 1)

      - name: Run Pytest inside container
        run: docker-compose exec -T app pytest -v

      - name: Stop and clean up containers
        if: always()
        run: docker-compose down
